toolpath_control_params:
    force_ctrl_damping: 1.0e+4 # N / (m/s)
    force_epsilon: 10.0 # N
    moveL_speed_lin: 0.1 # m/s
    moveL_speed_ang: 0.1745 # rad/s # 10.0 deg/sec
    load_speed: 0.001 # m/s
    unload_speed: 0.01 # m/s
    disable_f_ctrl: True


work_offset:
    pos: [1.5, 0.0, 1.5] # m
    euler_deg: [0.0, 0.0, 0.0] # deg

tool_offset:
    pos: [0.0, 0.0, 0.0] # m
    euler_deg: [0.0, 180.0, 0.0] # deg

ft_offset:
    pos: [0.0, 0.0, 0.0] # m
    euler_deg: [0.0, 0.0, 0.0] # deg